 
# this file is automatically generated. Do not edit


include C:/ScriptGSX2-3/GSX2-3Stream/AM5728_VSB/mk/_PREBUILD_GENHEADERS_VXBUS_BUSLIB_src_diab_i2c.mk 
include C:/ScriptGSX2-3/GSX2-3Stream/AM5728_VSB/mk/_PREBUILD_GENHEADERS_VXBUS_BUSLIB_src_diab_pci.mk 
include C:/ScriptGSX2-3/GSX2-3Stream/AM5728_VSB/mk/_PREBUILD_GENHEADERS_VXBUS_BUSLIB_src_diab_spi.mk 
include C:/ScriptGSX2-3/GSX2-3Stream/AM5728_VSB/mk/_PREBUILD_GENHEADERS_VXBUS_BUSLIB_src_diab_fdt.mk



   



