

/* this file is automatically generated */


Layer Layer::BRANSON_LAYER_BRANSONWEBSERVICES {
}




/*********************************
 Component INCLUDE_WEBCLI_BRANSONWEBSERVICES 
 original object sources located at 
  "C:/ScriptGSX2-3/GSX2-3Stream/_Branson_Driver_Layer/BRANSON_DRV/src/BransonWebservices/cdf/40bransonwebservices.cdf" 26 44  
**********************************/
Component	INCLUDE_WEBCLI_BRANSONWEBSERVICES {
		LAYER += Layer::BRANSON_LAYER_BRANSONWEBSERVICES
		LAYER_SOURCE		{ "C:/ScriptGSX2-3/GSX2-3Stream/_Branson_Driver_Layer/BRANSON_DRV/src/BransonWebservices/cdf/40bransonwebservices.cdf" 26 44 }
}


/*********************************
 Layer Layer::BRANSON_LAYER_BRANSONWEBSERVICES 
 original object sources located at 
  "C:/ScriptGSX2-3/GSX2-3Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_BRANSON_LAYER_BRANSONWEBSERVICES.tmp" 13 15  
**********************************/
Layer	Layer::BRANSON_LAYER_BRANSONWEBSERVICES {
		LAYER += Layer::BRANSON_LAYER_BRANSONWEBSERVICES
		LAYER_SOURCE		{ "C:/ScriptGSX2-3/GSX2-3Stream/AM5728_VSB/krnl/cdf/cdf_PRENOBUILD_BRANSON_LAYER_BRANSONWEBSERVICES.tmp" 13 15 }
}
