/*-----------------------------------------------------------------------------
 * Copyright                acontis technologies GmbH, Weingarten, Germany
 * Response                 Paul Bussmann
 * Description              EtherCAT Master type definition checks
 *---------------------------------------------------------------------------*/

#ifndef INC_ECTYPE_SANITYCHECK
#define INC_ECTYPE_SANITYCHECK

/*-SANITY CHECKS-------------------------------------------------------------*/
#if (defined __GNUC__) || (defined __ICCARM__)
#define ASSERT_CONCAT_(a, b) a##b
#define ASSERT_CONCAT(a, b) ASSERT_CONCAT_(a, b)
#define SANITY_CHECK_STRUCTURE_SIZE_ASSERT(expr) enum { ASSERT_CONCAT(assert_line_, __LINE__) = 1/(!!(expr)) }
#define SANITY_CHECK_STRUCTURE_SIZE(type, size) \
		SANITY_CHECK_STRUCTURE_SIZE_ASSERT(sizeof(type)==size);
#define SANITY_CHECK_VALUE_EQUAL(name, set, act) \
		SANITY_CHECK_STRUCTURE_SIZE_ASSERT(set==act);
#else
#define SANITY_CHECK_VALUE_EQUAL(name, type, size) \
  typedef char EC_T_CHECK_UPPER_##name[##type-##size+1];\
  typedef char EC_T_CHECK_LOWER_##name[##size-##type+1];
#define SANITY_CHECK_STRUCTURE_SIZE(type, size) SANITY_CHECK_VALUE_EQUAL(##type, sizeof(##type), ##size)
#endif

/* check sizeof(EC_T_UINT64) == 8 */
SANITY_CHECK_STRUCTURE_SIZE(EC_T_UINT64, 8)

/* check sizeof(EC_T_INT64) == 8 */
SANITY_CHECK_STRUCTURE_SIZE(EC_T_INT64, 8)

/* check sizeof(EC_T_STATE) == 4 */
SANITY_CHECK_STRUCTURE_SIZE(EC_T_STATE, 4)

/* check SIZEOF_EC_T_SLAVES_STATECHANGED_NTFY_DESC */
SANITY_CHECK_STRUCTURE_SIZE(EC_T_SLAVES_STATECHANGED_NTFY_DESC, SIZEOF_EC_T_SLAVES_STATECHANGED_NTFY_DESC(MAX_SLAVES_STATECHANGED_NTFY_ENTRIES))

/* check SIZEOF_EC_T_SLAVES_PRESENCE_NTFY_DESC */
SANITY_CHECK_STRUCTURE_SIZE(EC_T_SLAVES_PRESENCE_NTFY_DESC, SIZEOF_EC_T_SLAVES_PRESENCE_NTFY_DESC(MAX_SLAVES_PRESENCE_NTFY_ENTRIES))

SANITY_CHECK_STRUCTURE_SIZE(EC_T_PROCESS_VAR_INFO_EX, 160)
SANITY_CHECK_STRUCTURE_SIZE(EC_T_GET_SLAVE_INFO, 332)
SANITY_CHECK_STRUCTURE_SIZE(EC_T_CFG_SLAVE_INFO, 248)
SANITY_CHECK_STRUCTURE_SIZE(EC_T_BUS_SLAVE_INFO, 108)
SANITY_CHECK_STRUCTURE_SIZE(ETHERNET_FRAME, 14)
SANITY_CHECK_STRUCTURE_SIZE(ETHERNET_88A4_FRAME, 16)
SANITY_CHECK_STRUCTURE_SIZE(ETYPE_VLAN_HEADER, 4)

SANITY_CHECK_STRUCTURE_SIZE(ETHERCAT_MBOX_HEADER, 6)

SANITY_CHECK_STRUCTURE_SIZE(EC_T_STATISTIC, 8)
SANITY_CHECK_STRUCTURE_SIZE(EC_T_STATISTIC_TRANSFER, 16)
SANITY_CHECK_STRUCTURE_SIZE(EC_T_STATISTIC_TRANSFER_DUPLEX, 32)
SANITY_CHECK_STRUCTURE_SIZE(EC_T_MAILBOX_STATISTICS, 256)
SANITY_CHECK_STRUCTURE_SIZE(EC_T_BUS_DIAGNOSIS_INFO, 68)
SANITY_CHECK_STRUCTURE_SIZE(EC_T_MASTER_INFO, 456)

/* EC_T_MBXTFER differs for 32 / 64 bit. Intentionally not checked. */

/* check EC_FOE_HDR == 6 */
SANITY_CHECK_STRUCTURE_SIZE(EC_FOE_HDR, 6)

#undef SANITY_CHECK_STRUCTURE_SIZE

SANITY_CHECK_VALUE_EQUAL(DEVICE_STATE_INIT, DEVICE_STATE_INIT, eEcatState_INIT)
SANITY_CHECK_VALUE_EQUAL(DEVICE_STATE_PREOP, DEVICE_STATE_PREOP, eEcatState_PREOP)
SANITY_CHECK_VALUE_EQUAL(DEVICE_STATE_SAFEOP, DEVICE_STATE_SAFEOP, eEcatState_SAFEOP)
SANITY_CHECK_VALUE_EQUAL(DEVICE_STATE_OP, DEVICE_STATE_OP, eEcatState_OP)

#undef SANITY_CHECK_VALUE_EQUAL

#endif /* INC_ECTYPE_SANITYCHECK */
