# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_IPNET_TFTP  {}
set _VSB_LAYER_CDFPATH_IPNET_TFTP [concat  $_VSB_LAYER_CDFPATH_IPNET_TFTP C:/WindRiverSR500/vxworks-7/pkgs/net/ipnet-1.1.1.3/app/tftp-1.0.1.4/cdf]
