# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_FONT  {}
set _VSB_LAYER_CDFPATH_FONT [concat  $_VSB_LAYER_CDFPATH_FONT C:/WindRiverSR500/vxworks-7/pkgs/ui/font-1.0.0.1/cdf]
