# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_TILCON  {}
set _VSB_LAYER_CDFPATH_TILCON [concat  $_VSB_LAYER_CDFPATH_TILCON C:/WindRiverSR500/vxworks-7/pkgs/ui/tilcon-7.0.0.1/cdf]
