# this file is automatically generated by mk/krnl/rules.layers.mk
VSBL_CDFPATH_BRANSON_LAYER_BRANSONHTTP =
VSBL_CDFPATH_BRANSON_LAYER_BRANSONHTTP += C:/ScriptGSX2-3/GSX2-3Stream/_Branson_Driver_Layer/BRANSON_DRV/src/BransonHTTP/cdf
