# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_BRANSON_LAYER_TIDSSFB  {}
set _VSB_LAYER_CDFPATH_BRANSON_LAYER_TIDSSFB [concat  $_VSB_LAYER_CDFPATH_BRANSON_LAYER_TIDSSFB C:/ScriptGSX2-3/GSX2-3Stream/_Branson_Driver_Layer/BRANSON_DRV/src/tidss/cdf]
