# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_IMAGE  {}
set _VSB_LAYER_CDFPATH_IMAGE [concat  $_VSB_LAYER_CDFPATH_IMAGE C:/WindRiverSR500/vxworks-7/pkgs/ui/image-1.0.0.2/cdf]
