# this file is automatically generated by mk/krnl/rules.layers.mk
VSBL_CDFPATH_STACKTRACE =
VSBL_CDFPATH_STACKTRACE += C:/WindRiverSR500/vxworks-7/pkgs/rttools/stacktrace-1.0.1.6/src/osconfig/vxworks/cdf
