# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_END_LIB  {}
set _VSB_LAYER_CDFPATH_END_LIB [concat  $_VSB_LAYER_CDFPATH_END_LIB C:/WindRiverSR500/vxworks-7/pkgs/net/end-1.2.5.0/lib/cdf]
